swipe:
  3:
    left:
      command: "xdotool key alt+Left"
    right:
      command: "xdotool key alt+Right"
    up:
      command: "xdotool key ctrl+t"
    down:
      command: "xdotool key ctrl+w"
  4:
    left:
      command: "xdotool key alt+Shift+Tab"
    right:
      command: "xdotool key alt+Tab"
    up:
      command: "xdotool key super"
    down:
      command: "xdotool key super"

pinch:
  2:
    in:
      command: "xdotool key ctrl+plus"
      threshold: 0.1
    out:
      command: "xdotool key ctrl+minus"
      threshold: 0.1