swipe:
  4:
    up:
      sendkey: "CTRL+LEFTALT+Up"
    down:
      sendkey: "CTRL+LEFTALT+Down"
    left:
      sendkey: "CTRL+LEFTMETA+RIGHT"
    right:
      sendkey: "CTRL+LEFTMETA+LEFT"
  3:
    left:
      sendkey: "LEFTALT+RIGHT"
    right:
      sendkey: "LEFTALT+LEFT"
    up:
      sendkey: "CTRL+T"
    down:
      sendkey: "CTRL+W"

pinch:
  2:
    in:
      sendkey: "CTRL+KPPLUS"
      threshold: 0.1
    out:
      sendkey: "CTRL+MINUS"
      threshold: 0.1
